### ISSUE TITLE
Problem to save AuditEvent

### ISSUE THREAD

**Issue by giovannicandido** [atende/audit-mq-collector#6]
In production
The follow error below happens.
Maybe the dependency on _audit-model_ is not in the bundle

> ```
> 2016-08-04 14:22:32.126 WARN 3192 — [SimpleAsyncTaskExecutor-5321] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
> 
> org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
> at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:865)
> at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:803)
> at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:691)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:93)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:183)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1358)
> at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:661)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1102)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1086)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:93)
> at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1203)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: br.pucminas.icei.audition.AuditCollectorException: N?o pode salvar AuditEvent
> at br.pucminas.icei.audition.quee.Process.onMessage(Process.java:36)
> at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:800)
> ... 10 common frames omitted
> Caused by: org.springframework.amqp.support.converter.MessageConversionException: failed to resolve class name. Class not found [info.atende.audition.model.AuditEvent]
> at org.springframework.amqp.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:59)
> at org.springframework.amqp.support.converter.DefaultJackson2JavaTypeMapper.toJavaType(DefaultJackson2JavaTypeMapper.java:28)
> at org.springframework.amqp.support.converter.Jackson2JsonMessageConverter.fromMessage(Jackson2JsonMessageConverter.java:91)
> at br.pucminas.icei.audition.quee.Process.onMessage(Process.java:32)
> ... 11 common frames omitted
> Caused by: java.lang.ClassNotFoundException: info.atende.audition.model.AuditEvent
> at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
> at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
> at org.springframework.amqp.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:56)
> ... 14 common frames omitted
> ```

**Comment by giovannicandido** [comment]
Problem solved when building in the latest dev
